site_name: My Docs
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true          
  - toc:
      permalink: true          
  - tables

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

# copyright: QFPay
site_name: QFPay Docs

theme:
  name: material
  custom_dir: custom_theme
  font:
    text: Roboto
    size: 14px
  # custom_dir: !ENV [THEME_DIR, "material"]
  logo: assets/logo.png
  palette: 
    # - primary: indigo
    # - primary: blue
    # - accent: blue
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/brightness-7
        name: Switch to light mode  
  features:
    - navigation.instant
   
    - navigation.tabs
    - navigation.sections
    # - navigation.expand
    # - navigation.indexes
    - navigation.top
    
    - toc.follow
    - toc.integrate

extra:
  robots: 'noindex,noarchive,nofollow'
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    # feedback:
    #   title: Was this page helpful?
    #   ratings:
    #     - icon: material/emoticon-happy-outline
    #       name: This page was helpful
    #       data: 1
    #       note: >-
    #         Thanks for your feedback!
    #     - icon: material/emoticon-sad-outline
    #       name: This page could be improved
    #       data: 0
    #       note: >- 
    #         Thanks for your feedback! Help us improve this page by
    #         using our <a href="..." target=_blank>feedback form</a>.
  disable_footer_link: true

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  
nav:
    - Home: 'index.md'
    - 'POS':
      - 'pos/ecr.md'
    - 'Subscription':
      - 'subscription/integration.md'
    - 'CDI':
      - 'cdi/integration.md'
      - 'cdi/test values.md'
      - 'cdi/transaction data file specification.md'
      - 'cdi/merchant data file specification.md'
    - 'Payment API':
        - 'integration/payment.md'
        - 'integration/alipay service window h5.md'
        - 'integration/Transaction Enquiry.md'
    - 'Checkout Page': 'https://checkout-sdk.qfapi.com/'
    - 'Android SDK': 'https://android-sdk.qfapi.com/'

plugins:
  - git-revision-date-localized:
      type: iso_date
  - tags
  - search

# Hooks
hooks:
  - src/custom_theme/hooks/shortcodes.py
